version: '3.7'
services:
  database:
    container_name: statusmanager-database
    image: postgres:15
    environment:
      POSTGRES_DB: statusmanager
      POSTGRES_USER: statusmanager
      POSTGRES_PASSWORD: statusmanager
    ports:
      - "5432:5432"
    networks:
      - statusmanager-network
networks:
  statusmanager-network: